services:
    database:
        image: postgres:17.4-alpine3.21
        ports:
            - "5433:5432"
        env_file:
            - ./.env.development

    backend:
         build: 
             context: ./backend
         ports:
             - "8080:3000"
         env_file:
             - ./.env.development
         develop:
             watch:
                 - action: sync
                   path: ./backend/src
                   target: /app/src
                   ignore:
                     - node_modules/
                 - action: rebuild
                   path: package.json
         depends_on:
             - database
