services:
    database:
        image: postgres
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    backend:
         build: 
             context: ./backend
         ports:
             - "3000:3000"
         environment:
             - PORT=3000
             - POSTGRES_USER=postgres
             - POSTGRES_PASSWORD=postgres
             - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5433/postgres?schema=public
         develop:
             watch:
                 - action: sync
                   path: ./backend/src
                   target: /app/src
                   ignore:
                     - node_modules/
                 - action: rebuild
                   path: package.json
         depends_on:
             - database
