version: '3.8'

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    # backend:
    #     build: 
    #         context: .
    #     ports:
    #         - "3000:3000"
    #     environment:
    #         - DATABASE_URL="postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
    #     depends_on:
    #         - postgres